### ISSUE TITLE
convert check for understandings into questions (Part D)

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1006]
Related to #575 
## Task:

 Change the linked outlined below so that your PR ensures:

- It’s Check for Understanding section tells apprentices to form small groups and answer at least 2 long-answer or more shorter-answer questions so they can self-assess whether they understand the material.
- The questions should check whether they’ve achieved **every** part of the “objectives” section at the beginning of the outline.
- The updated CFU section should not change the total “projected time” dramatically. If the “projected time” changes as a result, be sure to update it.
- Don’t just delete what’s already in CFU. (See next points)
- if the CFU section already contains something valuable, we can consider putting it in the independent practice or challenge section instead. Don’t forget to adjust projected time.
- if the CFU section contains something less valuable, you can move it to the supplemental resources section.
- if you finish, or notice a Check for Understanding already looks fine, please check it off on this list or let a Techtonica admin know it's complete
- A single PR can be made for two edited Check for Understanding sections, earning you a Hacktoberfest contribution.

* Here is a great example of what we want for our Check for Understanding sections from [our TDD outline](https://github.com/Techtonica/curriculum/blob/master/testing-and-tdd/testing-and-tdd.md):
### Check for Understanding

Form small groups and discuss:
- What is an automated test?
- What is TDD?
- What are some advantages of TDD?
- What are some disadvantages of TDD?
- Where should your tests live in your project?
- How do you run your tests?

——————————-

- [x] https://github.com/Techtonica/curriculum/blob/master/github-collaboration/github-collaboration.md
- [x] https://github.com/Techtonica/curriculum/blob/master/reading-and-writing-documentation/documentation.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-2.md

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by IngridGdesigns** [comment]
Hi Alina, 

I would like to work on this issue!

**Comment by IngridGdesigns** [comment]
Hi Alina, I made two additional pull requests to add Check for understanding questions to the following docs:
 https://github.com/Techtonica/curriculum/blob/master/reading-and-writing-documentation/documentation.md
https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-2.md

Let me know if there is anything else I need to change / add!
