### ISSUE TITLE
convert check for understandings into questions (Part S)

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1022]
Related to #575 
## Task:

 Change the linked outlines below so that your PR ensures:

- Its Check for Understanding section tells apprentices to form small groups and answer at least 2 long-answer or more shorter-answer questions so they can self-assess whether they understand the material.
- The questions should check whether they’ve achieved **every** part of the “objectives” section at the beginning of the outline.
- The updated CFU section should not change the total “projected time” dramatically. If the “projected time” changes as a result, be sure to update it.
- Don’t just delete what’s already in CFU. (See next points)
- if the CFU section already contains something valuable, we can consider putting it in the independent practice or challenge section instead. Don’t forget to adjust projected time.
- if the CFU section contains something less valuable, you can move it to the supplemental resources section.
- if you finish, or notice a Check for Understanding already looks fine, please check it off on this list or let a Techtonica admin know it's complete
- A single PR can be made for two edited Check for Understanding sections, earning you a Hacktoberfest contribution.

* Here is a great example of what we want for our Check for Understanding sections from [our TDD outline](https://github.com/Techtonica/curriculum/blob/master/testing-and-tdd/testing-and-tdd.md):
### Check for Understanding

Form small groups and discuss:
- What is an automated test?
- What is TDD?
- What are some advantages of TDD?
- What are some disadvantages of TDD?
- Where should your tests live in your project?
- How do you run your tests?

——————————-

- [x] https://github.com/Techtonica/curriculum/blob/master/algorithms/searching.md
- [ ] https://github.com/Techtonica/curriculum/blob/master/algorithms/sorting.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/interviewing/technical-interviewing.md

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by thisLinda** [comment]
Hi Alina, I'd like to pick up this issue.

**Comment by thisLinda** [comment]
Never mind, I see that checks for understanding are already completed in each.

**Comment by alodahl** [comment]
Actually @thislinda, would you be able to replace the Sorting cfu with questions that compare and contrast the different sorting algos?

**Comment by thisLinda** [comment]
I'm on it!

**Comment by thisLinda** [comment]
Six days later I'm checking back in with the intention of offering any other (simple) help you might need. I _thought_ I submitted a pull request for this issue but I don't see it! If I missed something and you've got the time to up date me please let me know.

**Comment by alodahl** [comment]
@thisLinda it looks like you committed it to your own forked repo, but you still need to make a pull request to Techtonica/master. Click the pull request button, and it should choose Techtonica/master by default. Please write ' fixes #1022'  in the description text area when you make your PR.
![image](https://user-images.githubusercontent.com/29131689/67820837-0f3a2880-fa78-11e9-95c5-8de718e5a71e.png)

**Comment by thisLinda** [comment]
🤦🤦🤦

**Comment by thisLinda** [comment]
Hi Alina!

Now that the crush of Hacktober is completed and you maybe have time to
think again I'd like to offer my assistance with Techtonica and the
project. I am self-learning code and consider myself an advanced beginner
so I'm not available to solve your big code issues but I can help with the
little stuff. For instance Issues 1099 and 1098 seem to be something I can
easily do! Now that Hacktoberfest is done is it necessary to continue to
have the issue assigned or is it okay to just go ahead and do it?

Your project is amazing and I look forward to contributing!

Thank you,
Linda

**Comment by alodahl** [comment]
@thisLinda yes, please go ahead!  Thanks for your help 🤸‍♀️
