### ISSUE TITLE
React Part 3 - Components & Hierarchies

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/curriculum#1336]
**Task**:  The previous contributor was unable to complete this issue, but they got quite far. Please:
- [ ] Make edits to this outline: https://github.com/Techtonica/curriculum/blob/master/react-js/react-part-3-component-hierarchies.md
- [ ] Make any changes needed so the Acceptance Criteria below is fulfilled in the outline.
- [ ] Address all the unresolved comments found here: https://github.com/Techtonica/curriculum/pull/1347

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum/blob/main/CONTRIBUTING.md
_____________________

## Original issue description:

_Child task of Epic #1301_

The previous two lessons focused on props and state inside of a single component. Now we need to expand on that foundation to cover how props and state are passed along component hierarchies and when it makes sense to split some JSX into a new component.

Use our [Lesson Template v2](https://github.com/Techtonica/curriculum/blob/master/_templates/lesson-v2.md)

## Topics to Cover
- Different between Components and built-in JSX tags like `<button>`
- How to refactor code where all JSX is in one component into separate components
  - Reasons to do so, duplication. The code exercise could be turning a map function that creates a snippet JSX to one that creates instances of another component
  - Keeping components small and single-purpose
- `props.children`
- Using 3p components like `reactstrap`
- Passing callback functions to have children allow the parent to decide what an onClick does
- Passing along state from a parent into a child component

## Example Code
- Example code should run in a CodePen or similar. It should not need Babel/Webpack, etc 
- Class components only (no Functional)

This lesson should go in the `./react-js/react-part-3-hierarchies.md` and a link added to the main README.md along with the other React lessons.

**Comment by annu12340** [comment]
I would like to work on this issue

**Comment by annu12340** [comment]
Could you please elaborate on what is meant by " Using 3p components like reactstrap ". I didn't get it

**Comment by Kundan28** [comment]
> Could you please elaborate on what is meant by " Using 3p components like reactstrap " and about the refactoring of the code. I didn't get it

@vegetabill

**Comment by ashishnagpal2498** [comment]
I think what he mean to say is using 3rd party Components like Reactstrap which include inbuilt CSS in their component.

**Comment by Kundan28** [comment]
> I think what he mean to say is using 3rd party Components like Reactstrap which include inbuilt CSS in their component.

Yeah, I to think so...

**Comment by Kundan28** [comment]
@annu12340 Do you want to work on this issue ?

**Comment by annu12340** [comment]
Yes

**Comment by Kundan28** [comment]
@annu12340 Please go through https://bit.ly/2wQxqLy and after you have filled the forms mentioned inside you could start working on this issue.

**Comment by annu12340** [comment]
> @annu12340 Please go through https://bit.ly/2wQxqLy and after you have filled the forms mentioned inside you could start working on this issue.

I have already done that part :)

**Comment by Kundan28** [comment]
> > @annu12340 Please go through https://bit.ly/2wQxqLy and after you have filled the forms mentioned inside you could start working on this issue.
> 
> I have already done that part :)

Okay, then you could start working on the issue.
