### ISSUE TITLE
Update table of contents to reflect roadmap curriculum order

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#460]
[Here is the Techtonica Program Roadmap.](https://docs.google.com/spreadsheets/d/1vIr3fiKa_jxzy7qtFsiE5hEJbiTXwc1LYxbfsHOYD6U/edit#gid=0)

- [x] Make sure the['table of contents' in the project ReadMe.md](https://github.com/Techtonica/curriculum#table-of-contents) reflects the order of lesson outlines in the Roadmap.
- [x] Make sure the 'table of contents' topics are linked to the proper lesson outline - the outline link in the Roadmap is more likely to be correct.
- [x] Delete or ask @alodahl about topics that have no outline or folder - Python and Django are an example of lesson ideas that never fit into the final curriculum plan.  
- If it has no repo file, but it is marked red in the Road Map, create an entry for it in the table of contents, but with no link yet.

For more detailed directions, see: https://github.com/Techtonica/curriculum#volunteering
