### ISSUE TITLE
convert check for understandings into questions (multiple assignees encouraged)

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#700]
Related to #575 
## Task:

 Change the linked outlines below so that your PR ensures:

Look through topic outlines, and change **any 2** so that your PR ensures:
- It’s Check for Understanding section tells apprentices to form small groups and answer at least 2 long-answer or more shorter-answer questions so they can self-assess whether they understand the material.
- The questions should check whether they’ve achieved **every** part of the “objectives” section at the beginning of the outline.
- The updated CFU section should not change the total “projected time” dramatically. If the “projected time” changes as a result, be sure to update it.
- Don’t just delete what’s already in CFU. (See next points)
- if the CFU section already contains something valuable, we can consider putting it in the independent practice or challenge section instead. Don’t forget to adjust projected time.
- if the CFU section contains something less valuable, you can move it to the supplemental resources section.
- if you finish, or notice a Check for Understanding already looks fine, please check it off on this list or let a Techtonica admin know it's complete
- A single PR can be made for two edited Check for Understanding sections, earning you a Hacktoberfest contribution.

* Here is a great example of what we want for our Check for Understanding sections from [our TDD outline](https://github.com/Techtonica/curriculum/blob/master/testing-and-tdd/testing-and-tdd.md):
### Check for Understanding

Form small groups and discuss:
- What is an automated test?
- What is TDD?
- What are some advantages of TDD?
- What are some disadvantages of TDD?
- Where should your tests live in your project?
- How do you run your tests?

——————————-

Topic outlines whose materials sections not been reviewed:
- [x] https://github.com/Techtonica/curriculum/blob/master/personal-brand/personal-branding.md
- [x] https://github.com/Techtonica/curriculum/blob/master/professionalism/professionalism.md
- [x] https://github.com/Techtonica/curriculum/blob/master/ergonomics/ergonomics.md
- [x] https://github.com/Techtonica/curriculum/blob/master/learning-to-learn/learning-to-learn.md
- [x] https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/roles-in-tech.md
- [x] https://github.com/Techtonica/curriculum/blob/master/welcome-tips-rules/tech-industry-tips.md

- [x] https://github.com/Techtonica/curriculum/blob/master/command-line/command-line-interface.md
- [x] https://github.com/Techtonica/curriculum/blob/master/command-line/vim.md 
- [x] https://github.com/Techtonica/curriculum/blob/master/command-line/keyboard-shortcuts.md

- [x] https://github.com/Techtonica/curriculum/blob/master/projects/first-assessment.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/pair-programming/pair-programming.md
- [x] https://github.com/Techtonica/curriculum/blob/master/html/html.md
- [x] https://github.com/Techtonica/curriculum/blob/master/git-version-control/git-version-control.md
- [x] https://github.com/Techtonica/curriculum/blob/master/projects/recipe-page/phase-1-html-prompt.md
- [x] https://github.com/Techtonica/curriculum/blob/master/css/css.md
- [x] https://github.com/Techtonica/curriculum/blob/master/chrome-developer-tools/chrome-developer-tools.md
- [x] https://github.com/Techtonica/curriculum/blob/master/projects/recipe-page/phase-2-css-prompt.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/diversity-inclusion-bias/inclusion.md
- [x] https://github.com/Techtonica/curriculum/blob/master/seo/seo.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/personal-brand/personal-branding.md
- [x] https://github.com/Techtonica/curriculum/blob/master/writing-readable-code/writing-readable-code.md
- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-1.md
- [x] https://github.com/Techtonica/curriculum/blob/master/interviewing/whiteboarding.md
- [x] https://github.com/Techtonica/curriculum/blob/master/interviewing/week-3-whiteboard-challenges.md
- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-3.md
- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-4.md
- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-5.md
- [x] https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-6-object-literals.md
- [x] https://github.com/Techtonica/curriculum/blob/master/testing-and-tdd/testing-and-tdd.md
- [x] https://github.com/Techtonica/curriculum/blob/master/data-structures/stack.md

- [x] https://github.com/Techtonica/curriculum/blob/master/data-structures/trees.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/algorithms/intro-to-algorithms.md
- [x] https://github.com/Techtonica/curriculum/blob/master/resume-writing/resume-writing.md
 
- [x] https://github.com/Techtonica/curriculum/blob/master/women-in-tech-resources/resources-list.md

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by rudri182** [comment]
@alodahl May I work on this issue?

**Comment by alodahl** [comment]
@rudri182 just let us know which you’d like to work on so we can reserve them (check them off) fo you.

**Comment by rudri182** [comment]
I would like to work on [stacks outline](https://github.com/Techtonica/curriculum/blob/master/data-structures/stack.md)

**Comment by rudri182** [comment]
In stack.md the link in supplemental resources for [Cloudboost: Data Structures in JavaScript: Stacks & Queues](https://blog.cloudboost.io/data-structures-in-javascript-stacks-queues-75d83cd9f7e1) is not working.

**Comment by Kundan28** [comment]
> In stack.md the link in supplemental resources for [Cloudboost: Data Structures in JavaScript: Stacks & Queues](https://blog.cloudboost.io/data-structures-in-javascript-stacks-queues-75d83cd9f7e1) is not working.

Yeah, because they have made two different pages for Stack and Queue.
Do you want the link ?

**Comment by rudri182** [comment]
> > In stack.md the link in supplemental resources for [Cloudboost: Data Structures in JavaScript: Stacks & Queues](https://blog.cloudboost.io/data-structures-in-javascript-stacks-queues-75d83cd9f7e1) is not working.
> 
> Yeah, maybe because there are already two different pages for Stack and Queue.
> Do you want the link?

Yes, it would be easy to find some more exercise and questions. And can also put a link in the outline 😊, if it is permitted.

**Comment by Kundan28** [comment]
Here are both of the links...
https://blog.cloudboost.io/playing-with-data-structures-in-javascript-stack-a55ebe50f29d
https://blog.cloudboost.io/playing-with-data-structures-in-javascript-queue-70e1ee7d9d57

**Comment by rudri182** [comment]
> Here are both of the links...
> https://blog.cloudboost.io/playing-with-data-structures-in-javascript-stack-a55ebe50f29d
> https://blog.cloudboost.io/playing-with-data-structures-in-javascript-queue-70e1ee7d9d57

Thanks 😄

**Comment by rudri182** [comment]
@alodahl please reserve stacks outline for me. I have made some questions according to the TDD section. I will soon generate PR for it.

**Comment by Kumaranupam2020** [comment]
@alodahl i would like to work on this issue...

**Comment by alodahl** [comment]
@Kumaranupam2020 just let us know which you’d like to work on so we can reserve them (check them off) fo you.

**Comment by rudri182** [comment]
I have generated PR for this issue. Please review it? The PR number is #793

**Comment by raibove** [comment]
Can I work on this issue?
Topic: javascript-1  https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-1.md

**Comment by raibove** [comment]
@alodahl these topics look fine, please check:
https://github.com/Techtonica/curriculum/blob/master/women-in-tech-resources/resources-list.md
https://github.com/Techtonica/curriculum/blob/master/algorithms/intro-to-algorithms.md
https://github.com/Techtonica/curriculum/blob/master/data-structures/trees.md
https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-1.md

Can I work on these topics:
https://github.com/Techtonica/curriculum/blob/master/resume-writing/resume-writing.md
https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-4.md
https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-5.md

Javascript 4 and 5do not contain check for understanding, shall  I add it?

**Comment by alodahl** [comment]
@raibove yes please add them, thank you! 😁

**Comment by alodahl** [comment]
@Kundan28 @manaswinidas @Shwetha-Acharya @saberprashant @praveenscience please remember that for the multiple assignees encouraged issues, EACH FILE that is fixed according to the issue description should get them the GSSoC points.  So if raibove does all three of those topics, she'll get easy points X 3.

**Comment by Kundan28** [comment]
> @Kundan28 @manaswinidas @Shwetha-Acharya @saberprashant @praveenscience please remember that for the multiple assignees encouraged issues, EACH FILE that is fixed according to the issue description should get them the GSSoC points. So if raibove does all three of those topics, she'll get easy points X 3.

Okay, will make sure that points are given X 3.

**Comment by raibove** [comment]
@alodahl  These topics look fine, Please check:
https://github.com/Techtonica/curriculum/blob/master/professionalism/professionalism.md
https://github.com/Techtonica/curriculum/blob/master/ergonomics/ergonomics.md
https://github.com/Techtonica/curriculum/blob/master/learning-to-learn/learning-to-learn.md

**Comment by raibove** [comment]
@alodahl  Can I work on these topics once my PR gets merged https://github.com/Techtonica/curriculum/blob/master/css/css.md
https://github.com/Techtonica/curriculum/blob/master/html/html.md
https://github.com/Techtonica/curriculum/blob/master/command-line/command-line-interface.md
https://github.com/Techtonica/curriculum/blob/master/seo/seo.md

**Comment by raibove** [comment]
> @alodahl Can I work on these topics once my PR gets merged https://github.com/Techtonica/curriculum/blob/master/css/css.md
> https://github.com/Techtonica/curriculum/blob/master/html/html.md
> https://github.com/Techtonica/curriculum/blob/master/command-line/command-line-interface.md
> https://github.com/Techtonica/curriculum/blob/master/seo/seo.md

@alodahl can I work on these topics till my PR gets merged.

**Comment by alodahl** [comment]
@raibove you can start now 😊

**Comment by raibove** [comment]
This topic have questions in Check for Understanding but Projected Time is not updated 
https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-2.md
Is separate PR required for this topic?

Is Check for Understanding required for this topic: https://github.com/Techtonica/curriculum/blob/master/interviewing/week-3-whiteboard-challenges.md

**Comment by raibove** [comment]
Can I work on these topics:
https://github.com/Techtonica/curriculum/blob/master/diversity-inclusion-bias/inclusion.md
https://github.com/Techtonica/curriculum/blob/master/personal-brand/personal-branding.md
https://github.com/Techtonica/curriculum/blob/master/writing-readable-code/writing-readable-code.md
https://github.com/Techtonica/curriculum/blob/master/interviewing/whiteboarding.md
https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-3.md
https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-6-object-literals.md

**Comment by alodahl** [comment]
@raibove :
- week-3-whiteboard-challenges.md does not need a check for understanding. And Projected Time is not part of an issue, but thanks for noticing!
- You absolutely can work on those topics!

**Comment by sniemar** [comment]
Hello! Can I work on the Git Version Control outline? Here is the link https://github.com/Techtonica/curriculum/blob/master/git-version-control/git-version-control.md

**Comment by alodahl** [comment]
> Hello! Can I work on the Git Version Control outline? Here is the link https://github.com/Techtonica/curriculum/blob/master/git-version-control/git-version-control.md

That would be great!!  Thanks @sniemar.  How long do you think you need to complete it?

**Comment by sniemar** [comment]
@alodahl I will try to do it today.

**Comment by sniemar** [comment]
Can I work on this issue again? I would like to take these topics:
https://github.com/Techtonica/curriculum/blob/master/pair-programming/pair-programming.md
https://github.com/Techtonica/curriculum/blob/master/git-version-control/gitignore.md
https://github.com/Techtonica/curriculum/blob/master/reading-and-writing-documentation/documentation.md
