### ISSUE TITLE
Modify Machine Learning outline, make slideshow based on existing outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#720]
### Task:
Create a slideshow [here](https://docs.google.com/presentation/d/1bjU2En4KHo1gx085-NQISuyHuPSSnYhVYBOMz9pr050/edit#slide=id.p) based in [this outline](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/machine-learning.md), and make specific edits to the outline.

- [x] Create accompanying slideshow:
[Machine Learning Lesson Slideshow](https://docs.google.com/presentation/d/1bjU2En4KHo1gx085-NQISuyHuPSSnYhVYBOMz9pr050/edit#slide=id.p)

**Make the following changes to the outline:**
- [ ] Which companies use machine learning? - provide examples of how these companies use it

- [ ] Clarify the independent practice directions, and point to where the “mention” is coming from.  I couldn’t figure it out.

- [ ] Define “data analysis" with a link or a sentence in “prerequisites”

- [ ] Proofread

**Comment by yati1998** [comment]
@alodah can you assign me this issue?

**Comment by alodahl** [comment]
Remind me once you’ve finished the mongo issue, @yati1998

**Comment by rudri182** [comment]
I would like to work on this issue

**Comment by rudri182** [comment]
The above link of _Machine Learning_ is redirecting on this page. It is not opening machine learning. Is it this link?
[Machine Learning Engineer](https://github.com/Techtonica/curriculum/blob/master/roles-in-tech/machine-learning.md)

**Comment by alodahl** [comment]
@rudri182 https://github.com/Techtonica/curriculum/issues/706#issuecomment-480140295

**Comment by rudri182** [comment]
I am talking about the link given in the issue #720 description.

**Comment by rudri182** [comment]
May I start working on this issue?

**Comment by yati1998** [comment]
@alodahl I have done the mongo issue..  Can you assign me this?

**Comment by alodahl** [comment]
Can you give me the PR for your mongo issue? I can’t find it.

**Comment by rudri182** [comment]
Is this assigned to me ?

**Comment by alodahl** [comment]
No, @rudri182 , please fix all your PRs first.

**Comment by rudri182** [comment]
Ok.

**Comment by yati1998** [comment]
I have modified all my previous requests. so If you allow can I work on this now?

**Comment by yati1998** [comment]
@alodahl  I have modified the outline as well as the slideshow. Please review if any changes are required in the slideshow.

**Comment by saberprashant** [comment]
Hi @alodahl , should we close this issue now as a PR already being merged for the same?
Thanks 😄

**Comment by alodahl** [comment]
Yes @saberprashant if you every notice an issue has been merged and taken care of, go ahead and close it.
