### ISSUE TITLE
Add important workflow tips for VSCode

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#779]
## Task: 
The following VSCode skills need to be explained somewhere in our [VSCode Outline](https://github.com/Techtonica/curriculum/blob/master/vs-code/vscode.md). Decide the best place to put them, and explain the concepts for absolute beginners to coding. Be sure to update the projected time once you’ve added the new material.

 *VS Code and editor setup*
- [ ] - how to auto indent
- [ ] - how to indent multiple lines at a time (highlight several lines, even just partial lines, then press tab to indent the entire code block, or shift+tab to un-indent the entire code block; internal indentation of the block will be preserved. useful for copy and pasting code) 
- [ ] - code folding
- [ ] - autosave 
- [ ] - mention that VS Code preferences are literally a text file full of key-value pairs
- [ ] - define key value pair somewhere

**Comment by imskr** [comment]
I would like to work on this. Can I?

**Comment by saberprashant** [comment]
Hi @imskr , are you working on any other issue right now?

**Comment by imskr** [comment]
@saberprashant nope.
