### ISSUE TITLE
Create a lesson on JS object mapping in the context of an algorithm. 

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#795]
## Task: 
In our projects JavaScript folder, make a topic outline that guides apprentices in creating an object map to solve a problem, like “what is the most common character in this paragraph?”.  

This will come shortly after they first learn how to use objects in JavaScript,  to render lists in html, etc, so objects will still be a fairly new concept. 

- [ ] The topic outline should follow the format found in _templates/topic-outline.md. I recommend copying the template and replacing the content.

- [ ] you may write a tutorial or use an existing tutorial or resource online, as long as you cite the source and explain how to use it in the outline. If the outside source need further explanation for our beginner audience, please provide it.

- [ ] include a definition and explanation of *sets*.

- [ ] The topic outline should take 30-45 min for learners to complete.

- [ ] include a short video that explains this concept and provide the link in the materials section.

- [ ] include a slideshow that explains this concept and provide the link in the materials section. You may use a found slideshow if it explains the same concepts as the outline, but for visual learners.  If you prefer to make it, add your content to this file and rename it: https://docs.google.com/presentation/d/1fL2vgcI4uZPayAa-qCa34Rnuo0I3rfZIf7Lm7nnhNcU/edit?usp=sharing

**Comment by alodahl** [comment]
@tiffanyjstuart

**Comment by imskr** [comment]
Can i take this @alodahl ?

**Comment by Kundan28** [comment]
> Can i take this @alodahl ?

Wait for getting your two pending PRs to be approved and merged and then we can assign you this issue.

**Comment by imskr** [comment]
Should i place the outline in JavaScript folder with the name "JS Object Mapping" ? @alodahl

**Comment by alodahl** [comment]
could you put it in javascript/ and name it javascript-maps.md?

**Comment by imskr** [comment]
Yes @alodahl sure.
