### ISSUE TITLE
Add guided lesson to JS hash tables topic outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#796]
We received feedback that our [Hash Tables](https://github.com/Techtonica/curriculum/blob/master/data-structures/hash-tables.md) lesson explains the concepts of hash tables, but does little to guide learners in building or using one.

## Task: 
Add a guided practice section to the [Hash Tables topic outline](https://github.com/Techtonica/curriculum/blob/master/data-structures/hash-tables.md) that leads the apprentice through both creating and using a hash map.  Feel free to take ideas from Independent Practice if you think they'll be helpful, and change Independent Practice accordingly.

- [ ] You may write the Guided Practice from scratch or use an existing tutorial or resource online, as long as you cite the source and explain how to use it in the outline. If the outside source need further explanation for our beginner audience, please provide it.

- [ ]  Be sure to update Projected Time once you've added the new material.

- [ ] Add a short video that explains this concept and provide the link in the materials section. It can be an existing video, or you can make it yourself.

- [ ] Feel free to edit the slideshows under the Materials section if you think they can be improved.

- Possible resource: https://medium.freecodecamp.org/how-to-implement-a-simple-hash-table-in-javascript-cb3b9c1f2997

**Comment by alodahl** [comment]
@tiffanyjstuart

**Comment by rudri182** [comment]
May I work on this issue?

**Comment by rudri182** [comment]
May I put a link that you have mentioned in the description?

**Comment by rudri182** [comment]
Is this issue solving creating **hash maps** or **hash tables** ? First I added the tutorials describing hash tables but then I read _creating and using a hash map_. I have added both under the section of **guided practice** as the _link_ in the description is for _hash tables_.  So may I keep both or keep only for hash maps?

**Comment by alodahl** [comment]
Oops, sorry, it should be about hash tables. It would be nice to tell them the difference under Common Misconceptions.

**Comment by rudri182** [comment]
> Oops, sorry, it should be about hash tables. It would be nice to tell them the difference under Common Misconceptions.

It's okay. I am adding it to the **misconceptions** section. 😄
