### ISSUE TITLE
Convert first object-oriented project subject from restaurants to events

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#797]
Our apprentices' first JavaScript object-oriented project(oop project), Restaurant Recommender [Part 1](https://github.com/Techtonica/curriculum/blob/master/javascript/restaurant%20recommender/RestaurantRecommender%20-%20part1.md) and [Part 2](https://github.com/Techtonica/curriculum/blob/master/javascript/restaurant%20recommender/RestaurantRecommender-part2.md) are complete, but we are trying to condense as many lessons as we can into working on just a few projects.  We'd like to achieve this by converting the subject of the oop project files from restaurants to **events** so it can eventually be part of their [Eventonica Project](https://github.com/Techtonica/curriculum/blob/master/projects/eventonica-project.md) 2 weeks later.

## Task:

- [ ] Investigate the final object structure of an event in the [Eventonica Project](https://github.com/Techtonica/curriculum/blob/master/projects/eventonica-project.md).  The oop project should ask apprentices to create a simplified version of these event objects. In other words, it should be the same type of object, but stripped down to the 2 or 3 most important key-value pairs.  Once they move on to the Eventonica project, they should be able to easily add any remaining properties they may need.

- [ ] Be sure that all directions and examples in both [Part 1](https://github.com/Techtonica/curriculum/blob/master/javascript/restaurant%20recommender/RestaurantRecommender%20-%20part1.md) and [Part 2](https://github.com/Techtonica/curriculum/blob/master/javascript/restaurant%20recommender/RestaurantRecommender-part2.md) ask for the same type of work, but for an *event* app (like meetup.com) instead of a restaurant app.

- [ ] You can change the contents and name of the restaurant recommender files, or make brand new files in the javascript folder - whichever makes more sense to you.

**Comment by yati1998** [comment]
@alodahl  can I work on this issue? I have made my previous PR.

**Comment by alodahl** [comment]
@yati1998 your PR is changing something like 100 files - please fix that first.

**Comment by yati1998** [comment]
@alodahl  can I work on this issue? I have already made the required changes in the previous issue.

**Comment by yati1998** [comment]
@alodahl in the above issue, do you want me to replace both the restaurant project files with the event or shall I need to have new files in the javascript folder having the same contents as that of restaurants?
Do I need to have any change in the eventonica file? or just need to add a new events project file. What exactly the event should be? IT will be kind of you if you can help in this few doubts so that I can start working on the issue.

**Comment by yati1998** [comment]
@Kundan28  please can you help me clear my above doubts?

**Comment by alodahl** [comment]
@yati1998 we can answer your questions, but I am going to keep this issue open until you address my PR comments - many changes are required in #811 .

**Comment by yati1998** [comment]
@alodahl  sure.

**Comment by alodahl** [comment]
@yati1998 I wont have a chance to look at the mini project PR until tomorrow, so I wanted to give you a chance to work on this if you like. I will try to answer your questions the best I can.

**Comment by alodahl** [comment]
**"in the above issue, do you want me to replace both the restaurant project files with the event or shall I need to have new files in the javascript folder having the same contents as that of restaurants?"**

Either way is fine, just make sure they are about social events instead of restaurants.

**"Do I need to have any change in the eventonica file?"** No, you can leave Eventonica alone.

** What exactly the event should be? ** Please use the events API in the Eventonica project as your guide.

**Comment by yati1998** [comment]
@alodahl  do we need to have 2 parts of the project for events as we have for the restaurants?

**Comment by alodahl** [comment]
> @alodahl do we need to have 2 parts of the project for events as we have for the restaurants?

yes please

**Comment by yati1998** [comment]
@alodahl  I have made the PR. Please do review it when you get time. I am not sure whether I was correct in those changes. Please do suggest the changes required or do mention if I go wrong anywhere.
Thank you.
