### ISSUE TITLE
Create short mini project to prepare apprentices for their first JS OOP project

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#798]
## Task:
Create a short guided lesson that allows learners to use their new JS object-oriented programming skills to create a few *event* objects, push them to an array, then use jQuery to display the list of events to an html page.

Guide them step-by-step through making a javascript class for a social event, create new events and put them in the array, then iterate through the array and put the events into the html.

- [ ] This project should be seriously simple. Guide them through creating an event class, and events array, adding 3 or 4 new events, and then show them how to iterate though every event and inject it into an html file as list items using jQuery.
- [ ] Each event should be as simple as this example: 
 
      {
         name: "JS Study Group"
         description: "Beginners can study JavaScript together in a cozy environment".
      };

or

     {
        name: "The Nike Women's Half Marathon"
        description: "This 13.1 mile route begins in Union Square and weaves through Golden Gate Park.".
     };
 
- [ ] The new outline should follow the _templates/topic-outline.md template, and live in the javascript/ folder.
- [ ] There should be no css file. If you feel that some styling is essential, then add a rule or two inline on the html tags.
- [ ] This exercise should take between 1 and 2 hours - ideally 1.
- [ ] The mini project will come immediately after the [JS OOP lesson](https://github.com/Techtonica/curriculum/blob/master/javascript/javascript-7-oop.md). Make sure it is a prerequisite for your outline.
- [ ] The mini project should prepare them for [this larger project](https://github.com/Techtonica/curriculum/issues/797).

**Comment by alodahl** [comment]
@tiffanyjstuart

**Comment by yati1998** [comment]
@alodahl can I work on this project?

**Comment by yati1998** [comment]
@alodahl can u please assign me this issue?

**Comment by saberprashant** [comment]
Hi @yati1998 , are you working on anything else?

**Comment by yati1998** [comment]
Yes,  But I am done with that.  Just a final review is felt.  Meanwhile I can work on this,  if you assign it to me.

**Comment by saberprashant** [comment]
Okay @yati1998, I am assigning this to you, but please note that you have to complete that PR changes first (if @alodahl suggest any more changes).
Till then, you can start working on this one :)

**Comment by yati1998** [comment]
Thank you so much.  Yes sure I will make changes as asked.
