### ISSUE TITLE
Add treehouse resource to Relational Databases outline

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#800]
## Task:

 - [ ] Add this treehouse resource to [Relational Databases outline](https://github.com/Techtonica/curriculum/blob/master/databases/relational-databases.md) under lesson or guided practice - whichever makes the most sense: https://teamtreehouse.com/library/querying-relational-databases

- [ ] In addition to adding the link, introduce it by explaining the course, what they will learn and how long it will take them.

- [ ] Update the Projected Time section accordingly.

**Comment by raibove** [comment]
Can I work on this issue @alodahl

**Comment by alodahl** [comment]
Sure @raibove, just make sure to address your PR fixes first.
