### ISSUE TITLE
Replace outdated treehouse tutorial

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#959]
Curriculum feedback:  
- "The Treehouse tutorial that was part of the assessment due today is a bit outdated."
- "The 'CRUD workshop: connect Node and sqlite3 with Sequelize' was very outdated and didn’t help as being the foundation for our Assessment 8. It was supposed to be a starter code but I already spent half a day trying to fix its bugs and it’s not working yet."

**Task:**
- [ ] Checkout the treehouse tutorial in this [assessment outline](https://github.com/Techtonica/curriculum/blob/master/projects/minimal-api-project.md) and find a similar video, blog, or interactive tutorial that covers the same points and leaves them in a good place to continue the rest of the assessment.

- [ ] Once you've found a good one, follow it yourself to ensure it makes sense. This one was recommended to us, but please review it first: https://teamtreehouse.com/community/an-updated-guide-for-the-outdated-using-sql-and-nodejs-with-sequelize-workshop

- [ ] Replace the link and create a pull request.

Note:  You are welcome to write steps yourself instead of the tutorial, but it's likely that there is something already out there that would apply.

For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by Gustavomagalhaes** [comment]
Hi @alodahl I would like to help with this one
